language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: VOGPjgKERHSdgYyC8aIJLsCE9KFeiyd8ihUNhipq8PXkcmfYlPrBZJzIveHFgREITJYOL2l3rtpgDUoLc1cA4PfMyid8KmdP4+AohUw4QWIFixHUOf/BuTvAHaoqUwbnrPcUvk8FidCLC+z5A1BNhNMFkHTyoFfF7Xs9CKJjoJxUD+LJHEVM1m6VuP7wXR6nSYRR+xjF8XVivDmXF4exlGngBCMPu//zh9td0lKNTKenattv50FgIvQwtTcOpMjtY+hLuRp4Nl6zlTeH6ipV+fJgxjKW1kLHCPakCD4lU109QTbUA8ayErtobZuSQVYqyUpPyLP56IPU0s6w/QQgWrYS5rYgfRG1oYGQn7w3PmWjqg9NQK6+R05Kv8R0MFAswZoeh6CfoFAkZ5LpJIMipAa6W4e557hVZk1QXctMN2YmSSOWpUhgFawT6qQm6Ee3sXQny6wEO1vy8qdlzfG+ma1+H40UpUHVwA7LvqQV/utuOFgEntzEDvf4E94fCr8rozguyZbV198QGiOE6M1XsH2uNCkylh0BOiwwtVpL61d7lI7sx4KynrYZI5ntd1V7DEeg+Rv7FvS9PKcu5Lg/qmwqXgY5kW5KbGtbRjzzQPFj5/mJasCnfAOb9NG7Gvc4tY26jOOxcsd053zA76ApNHhyJSjJd07stOBrz8BTK4g=
  app: mexico-bandido
