language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: jG0gxbHIz3/v9pjaoMSp1peOsFj3IhuiXrZHBYkzWrjbnZ20enEYi9gOEOkNGAEwt58TLwsEqwKl03kcYt3XpXVSrT1/L+mpy5NC+d1bBhFTqTOlV2OO7mkXB/oWRNuXgiGgWvwNu9uvj0oFQMvJxEOxDJ7R78GKon04DqDbtYCxbM9E0ydWS4FIsoxN8CVII4cfxlGaPi9gUDmW6IOanPZuY8xflD+mw/7ch+xvvKTyAxrcPTJt0waOxqFx7zBGUNh0DG0BROJvtwXx1EIP2z3Y4iH+zZvh3ll2wiBws45eKfc8Cfcm3cVsWAOAs7wSdW/T6E9S6nwTY1rPIGg1+EKS5vsJ3ibQAivMRCNmW7Livmv4i1J3e0fglxx27zwSCbY/z/IF5czQpygEAymHG3ILZbfXhaAAzICZ8xhTT3n2E3EhstjYDXHAOKOeDzXgUqiBQQYBIHm56KXP7IKG5U/zxb09u5R3WFPfB2Vz0uZ7m3w72ukOAIG9VGKw9oGLKwbUIr3pw/IuMV2KUwv1v97aYKwD8LwqvJ46C1ACvo3y+K4v5yFdJNUFi8kRMeKkAVJo9C3/QR3m+ASf6IGmWm6W+qGERKqOToDrpvr0ewxY8zi2GiPsiaQoJs7w2HX/8//4UZssnnc4xoanq2+KtgJxFei0ykHpy6doq8wr4BQ=
  app: mexico-bandido
